// Sample data for the e-commerce app (without Firebase dependencies)

// Sample products
final List<Map<String, dynamic>> sampleProducts = [
  {
    'id': '1',
    'name': 'iPhone 15 Pro',
    'description': 'Latest iPhone with A17 Pro chip, titanium design, and advanced camera system',
    'price': 4999.0,
    'originalPrice': 5499.0,
    'image': 'https://via.placeholder.com/300x300/007AFF/FFFFFF?text=iPhone+15+Pro',
    'category_id': '1',
    'rating': 4.8,
    'reviewCount': 1247,
    'stock': 50,
    'color': 'Titanium',
    'specifications': {
      'screen': '6.1-inch Super Retina XDR',
      'storage': '128GB, 256GB, 512GB, 1TB',
      'camera': '48MP Main + 12MP Ultra Wide + 12MP Telephoto',
      'battery': 'Up to 23 hours video playback',
      'chip': 'A17 Pro chip',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '2',
    'name': 'MacBook Pro 14"',
    'description': 'Powerful laptop with M3 Pro chip, perfect for professionals and creators',
    'price': 8999.0,
    'originalPrice': 9999.0,
    'image': 'https://via.placeholder.com/300x300/FF6B35/FFFFFF?text=MacBook+Pro',
    'category_id': '2',
    'rating': 4.9,
    'reviewCount': 892,
    'stock': 30,
    'color': 'Space Gray',
    'specifications': {
      'screen': '14-inch Liquid Retina XDR display',
      'storage': '512GB, 1TB, 2TB SSD',
      'memory': '16GB, 32GB unified memory',
      'chip': 'M3 Pro chip',
      'battery': 'Up to 22 hours battery life',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '3',
    'name': 'iPad Air',
    'description': 'Versatile tablet with M2 chip, perfect for work and creativity',
    'price': 2999.0,
    'originalPrice': 3499.0,
    'image': 'https://via.placeholder.com/300x300/34C759/FFFFFF?text=iPad+Air',
    'category_id': '3',
    'rating': 4.7,
    'reviewCount': 567,
    'stock': 75,
    'color': 'Blue',
    'specifications': {
      'screen': '10.9-inch Liquid Retina display',
      'storage': '64GB, 256GB',
      'chip': 'M2 chip',
      'camera': '12MP Ultra Wide front camera',
      'battery': 'Up to 10 hours battery life',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '4',
    'name': 'Apple Watch Series 9',
    'description': 'Advanced smartwatch with health monitoring and fitness tracking',
    'price': 1499.0,
    'originalPrice': 1699.0,
    'image': 'https://via.placeholder.com/300x300/FF3B30/FFFFFF?text=Apple+Watch',
    'category_id': '4',
    'rating': 4.6,
    'reviewCount': 1234,
    'stock': 100,
    'color': 'Midnight',
    'specifications': {
      'screen': 'Always-On Retina display',
      'storage': '32GB',
      'sensors': 'Heart rate, ECG, Blood oxygen',
      'battery': 'Up to 18 hours battery life',
      'water': 'Water resistant 50m',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '5',
    'name': 'AirPods Pro',
    'description': 'Wireless earbuds with active noise cancellation and spatial audio',
    'price': 899.0,
    'originalPrice': 999.0,
    'image': 'https://via.placeholder.com/300x300/8E8E93/FFFFFF?text=AirPods+Pro',
    'category_id': '5',
    'rating': 4.5,
    'reviewCount': 2156,
    'stock': 150,
    'color': 'White',
    'specifications': {
      'audio': 'Active Noise Cancellation',
      'battery': 'Up to 6 hours listening time',
      'connectivity': 'Bluetooth 5.0',
      'features': 'Spatial audio, Transparency mode',
      'case': 'Wireless charging case',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '6',
    'name': 'iMac 24"',
    'description': 'All-in-one desktop with stunning display and powerful performance',
    'price': 3999.0,
    'originalPrice': 4499.0,
    'image': 'https://via.placeholder.com/300x300/007AFF/FFFFFF?text=iMac',
    'category_id': '2',
    'rating': 4.8,
    'reviewCount': 445,
    'stock': 25,
    'color': 'Blue',
    'specifications': {
      'screen': '24-inch 4.5K Retina display',
      'storage': '256GB, 512GB, 1TB, 2TB SSD',
      'memory': '8GB, 16GB unified memory',
      'chip': 'M3 chip',
      'camera': '1080p FaceTime HD camera',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '7',
    'name': 'Mac mini',
    'description': 'Compact desktop computer with M2 chip, perfect for home and office',
    'price': 2499.0,
    'originalPrice': 2799.0,
    'image': 'https://via.placeholder.com/300x300/8E8E93/FFFFFF?text=Mac+mini',
    'category_id': '2',
    'rating': 4.7,
    'reviewCount': 678,
    'stock': 40,
    'color': 'Space Gray',
    'specifications': {
      'storage': '256GB, 512GB, 1TB, 2TB SSD',
      'memory': '8GB, 16GB, 24GB unified memory',
      'chip': 'M2 chip',
      'ports': 'Thunderbolt 4, HDMI 2.0, USB-A',
      'connectivity': 'Wi-Fi 6E, Bluetooth 5.3',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '8',
    'name': 'iPad Pro 12.9"',
    'description': 'Most powerful iPad with M2 chip and Liquid Retina XDR display',
    'price': 4999.0,
    'originalPrice': 5499.0,
    'image': 'https://via.placeholder.com/300x300/34C759/FFFFFF?text=iPad+Pro',
    'category_id': '3',
    'rating': 4.9,
    'reviewCount': 789,
    'stock': 35,
    'color': 'Space Gray',
    'specifications': {
      'screen': '12.9-inch Liquid Retina XDR display',
      'storage': '128GB, 256GB, 512GB, 1TB, 2TB',
      'chip': 'M2 chip',
      'camera': '12MP Ultra Wide front camera',
      'connectivity': '5G, Wi-Fi 6E',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '9',
    'name': 'Apple TV 4K',
    'description': 'Streaming device with 4K HDR and Dolby Atmos sound',
    'price': 799.0,
    'originalPrice': 899.0,
    'image': 'https://via.placeholder.com/300x300/8E8E93/FFFFFF?text=Apple+TV',
    'category_id': '6',
    'rating': 4.4,
    'reviewCount': 1234,
    'stock': 80,
    'color': 'Black',
    'specifications': {
      'resolution': '4K HDR',
      'storage': '64GB, 128GB',
      'audio': 'Dolby Atmos',
      'connectivity': 'Wi-Fi 6, Bluetooth 5.0',
      'remote': 'Siri Remote',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': '10',
    'name': 'HomePod mini',
    'description': 'Smart speaker with Siri and immersive sound',
    'price': 599.0,
    'originalPrice': 699.0,
    'image': 'https://via.placeholder.com/300x300/FF6B35/FFFFFF?text=HomePod',
    'category_id': '6',
    'rating': 4.3,
    'reviewCount': 567,
    'stock': 120,
    'color': 'Space Gray',
    'specifications': {
      'audio': '360-degree sound',
      'assistant': 'Siri built-in',
      'connectivity': 'Wi-Fi 6, Bluetooth 5.0',
      'features': 'HomeKit hub, Intercom',
      'size': '3.3 inches tall',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
];

// Sample categories
final List<Map<String, dynamic>> sampleCategories = [
  {
    'id': '1',
    'name': 'iPhone',
    'image': 'https://via.placeholder.com/100x100/007AFF/FFFFFF?text=iPhone',
    'description': 'Latest iPhones with cutting-edge technology',
    'productCount': 3,
    'createdAt': DateTime.now().toIso8601String(),
    'lastUpdate': DateTime.now().toIso8601String(),
  },
  {
    'id': '2',
    'name': 'Mac',
    'image': 'https://via.placeholder.com/100x100/FF6B35/FFFFFF?text=Mac',
    'description': 'Powerful Mac computers for work and creativity',
    'productCount': 3,
    'createdAt': DateTime.now().toIso8601String(),
    'lastUpdate': DateTime.now().toIso8601String(),
  },
  {
    'id': '3',
    'name': 'iPad',
    'image': 'https://via.placeholder.com/100x100/34C759/FFFFFF?text=iPad',
    'description': 'Versatile tablets for work and play',
    'productCount': 2,
    'createdAt': DateTime.now().toIso8601String(),
    'lastUpdate': DateTime.now().toIso8601String(),
  },
  {
    'id': '4',
    'name': 'Apple Watch',
    'image': 'https://via.placeholder.com/100x100/FF3B30/FFFFFF?text=Watch',
    'description': 'Smartwatches for health and fitness',
    'productCount': 1,
    'createdAt': DateTime.now().toIso8601String(),
    'lastUpdate': DateTime.now().toIso8601String(),
  },
  {
    'id': '5',
    'name': 'AirPods',
    'image': 'https://via.placeholder.com/100x100/8E8E93/FFFFFF?text=AirPods',
    'description': 'Wireless audio accessories',
    'productCount': 1,
    'createdAt': DateTime.now().toIso8601String(),
    'lastUpdate': DateTime.now().toIso8601String(),
  },
  {
    'id': '6',
    'name': 'Home & Entertainment',
    'image': 'https://via.placeholder.com/100x100/FF6B35/FFFFFF?text=Home',
    'description': 'Smart home and entertainment devices',
    'productCount': 2,
    'createdAt': DateTime.now().toIso8601String(),
    'lastUpdate': DateTime.now().toIso8601String(),
  },
];

// Sample users
final List<Map<String, dynamic>> sampleUsers = [
  {
    'id': 'user1',
    'name': 'John Doe',
    'email': 'john.doe@example.com',
    'phone': '+971501234567',
    'address': {
      'street': '123 Sheikh Zayed Road',
      'city': 'Dubai',
      'state': 'Dubai',
      'zipCode': '12345',
      'country': 'UAE',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'user2',
    'name': 'Jane Smith',
    'email': 'jane.smith@example.com',
    'phone': '+971507654321',
    'address': {
      'street': '456 Al Wasl Road',
      'city': 'Dubai',
      'state': 'Dubai',
      'zipCode': '54321',
      'country': 'UAE',
    },
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
];

// Sample orders
final List<Map<String, dynamic>> sampleOrders = [
  {
    'id': 'order1',
    'userId': 'user1',
    'items': [
      {
        'productId': '1',
        'name': 'iPhone 15 Pro',
        'price': 4999.0,
        'quantity': 1,
        'image': 'https://via.placeholder.com/100x100/007AFF/FFFFFF?text=iPhone',
      },
      {
        'productId': '5',
        'name': 'AirPods Pro',
        'price': 899.0,
        'quantity': 1,
        'image': 'https://via.placeholder.com/100x100/8E8E93/FFFFFF?text=AirPods',
      },
    ],
    'total': 5898.0,
    'status': 'delivered',
    'shippingAddress': {
      'street': '123 Sheikh Zayed Road',
      'city': 'Dubai',
      'state': 'Dubai',
      'zipCode': '12345',
      'country': 'UAE',
    },
    'paymentMethod': 'credit_card',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'order2',
    'userId': 'user2',
    'items': [
      {
        'productId': '2',
        'name': 'MacBook Pro 14"',
        'price': 8999.0,
        'quantity': 1,
        'image': 'https://via.placeholder.com/100x100/FF6B35/FFFFFF?text=MacBook',
      },
    ],
    'total': 8999.0,
    'status': 'processing',
    'shippingAddress': {
      'street': '456 Al Wasl Road',
      'city': 'Dubai',
      'state': 'Dubai',
      'zipCode': '54321',
      'country': 'UAE',
    },
    'paymentMethod': 'paypal',
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
];

// Sample reviews
final List<Map<String, dynamic>> sampleReviews = [
  {
    'id': 'review1',
    'productId': '1',
    'userId': 'user1',
    'userName': 'John Doe',
    'rating': 5,
    'title': 'Amazing iPhone!',
    'comment': 'The iPhone 15 Pro is absolutely incredible. The camera quality is outstanding and the performance is lightning fast.',
    'createdAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'review2',
    'productId': '1',
    'userId': 'user2',
    'userName': 'Jane Smith',
    'rating': 4,
    'title': 'Great phone, expensive',
    'comment': 'Love the features and design, but it\'s quite expensive. Still worth it for the quality.',
    'createdAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'review3',
    'productId': '2',
    'userId': 'user1',
    'userName': 'John Doe',
    'rating': 5,
    'title': 'Perfect for work',
    'comment': 'The MacBook Pro handles everything I throw at it. Perfect for video editing and development.',
    'createdAt': DateTime.now().toIso8601String(),
  },
];
